name: Continuous Integration and Deployment to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Setup Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # Step 2: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 3: Change directory to ui-fundamentals
      - name: Change directory to ui-fundamentals
        run: cd ui-fundamentals && ls -la

      # Step 4: Check for merge conflicts
      - name: Check for merge conflicts
        run: |
          # Check if there are any merge conflicts
          if git diff --quiet; then
            echo "No merge conflicts found"
          else
            # Display merge conflicts and fail the workflow
            echo "Merge conflicts found. Please resolve conflicts and try again."
            git status
            exit 1
          fi

      # Step 5: Install project dependencies in ui-fundamentals
      - name: Install dependencies in ui-fundamentals
        working-directory: ui-fundamentals
        run: npm install

      # Step 6: Run tests in ui-fundamentals
      - name: Run tests in ui-fundamentals
        working-directory: ui-fundamentals
        run: npm test

      # Step 7: Lint code in ui-fundamentals
      - name: Lint code in ui-fundamentals
        working-directory: ui-fundamentals
        run: npm run lint

  deploy:
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # - name: Build Project
      #   run: |
      #     # Add commands to build your project artifacts here

      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.1.0

        with:
          publish-dir: ./ui-fundamentals/dist
          production-deploy: true

        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  # deploy_to_vercel:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   env:
  #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  #   steps:
  #     # Checkout code including submodules
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: recursive

  #     # Change directory to ui-fundamentals
  #     - name: Change directory to ui-fundamentals
  #       run: cd ui-fundamentals

  #     # Install Vercel CLI
  #     - name: Install Vercel CLI
  #       run: npm install --global vercel@latest

  #     # Pull Vercel Environment Information
  #     - name: Pull Vercel Environment Information
  #       run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

  #     # Build Project Artifacts
  #     - name: Build Project Artifacts
  #       run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

  #     # Deploy Project Artifacts to Vercel
  #     - name: Deploy Project Artifacts to Vercel
  #       run: |
  #         vercel deploy --prod --scope=./ui-fundamentals --token=${{ secrets.VERCEL_TOKEN }}
